#!/usr/bin/env bash
# Displays "FizzBuzz" when the number is amultiple of 3 aand 5.
# Displays "Fizz" when the number is amultiple if 3.
# Displays "Buzz " when the number is amultiple of 5.
# otherwise , displays the number.

for num in {1..100}
do 
	if (( num % 3== 0 && num % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( num % 3 ==0 ))
	then
		echo "Fizz"
	elif (( num % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo "$num"
	fi
done
