#!/bin/bash

# Configure localhost to resolve to 127.0.0.2
echo "127.0.0.2 localhost" | sudo tee -a /etc/hosts > /dev/null

# Configure facebook.com to resolve to 8.8.8.8
echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts > /dev/null
